apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
  labels:
    app: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: ghcr.io/cisco-open/martian-bank-demo-loan
          envFrom:
            - configMapRef:
                name: configmap-martianbank
          env:
            - name: SERVICE_PROTOCOL
              value: {{.Values.SERVICE_PROTOCOL}}
